name: Chrome

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  BROWSER_PRODUCT: chrome

jobs:
  Chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install & Build
        run: |
          npm install

      - name: Test
        run: |
          npm run test
        env:
          PUPPETEER_PRODUCT: chrome
