name: Firefox

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  BROWSER_PRODUCT: firefox

jobs:
  Firefox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install & Build & Test
        run: |
          npm install
          npm run test
        env:
          PUPPETEER_PRODUCT: firefox
